version: '3.3'
services:
  mysql_arbiter:
    image: mysql:5.7
    container_name: mysql_arbiter
    restart: always
    environment:
      MYSQL_DATABASE: 'arbiter'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  rabbit_arbiter:
    container_name: rabbit_arbiter
    image: "rabbitmq:3.8-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "dev"
    ports:
      - "15672:15672"
      - "5672:5672"