version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0
      - image: cimg/base:stable
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: arbiter
          MYSQL_USER: dev
          MYSQL_PASSWORD: password
    working_directory: ~/^repo
    environment:
      # Customize the JVM maximum heap limit
      SBT_VERSION: 1.5.5
      ARBITER2_IMAGE_NAME: mairo/arbiter2
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 20`;
            do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Prepare mysql for tests
          command: cat /dev/null | sbt flywayClean flywayMigrate
      - run:
          name: Sbt clean
          command: | 
            sbt clean
      - run:
          name: Run tests
          command: |
            sbt test
      - run:
          name: Create folder for test reports
          command: |
            mkdir -p scalaTest-reports
      - run:
          name: Save test results
          command: |
            cp -R target/test-reports/. scalaTest-reports/
      - run:
          name: Test results monitoring
          command: |
            cd scalaTest-reports
            ls -la
      - store_test_results:
          path: scalaTest-reports

  build-jar:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASS
    working_directory: ~/^repo
    environment:
      # Customize the JVM maximum heap limit
      SBT_VERSION: 1.5.5
      ARBITER2_IMAGE_NAME: mairo/arbiter2
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Prepare jar
          command: cat /dev/null | sbt 'set assembly/test := {}' clean assembly
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t $ARBITER2_IMAGE_NAME:latest .
      - run:
          name: Save docker image
          command: docker save -o image_arbiter2.tar $ARBITER2_IMAGE_NAME:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image_arbiter2.tar

  migrate-prod-mysq:
    environment:
      # Customize the JVM maximum heap limit
      SBT_VERSION: 1.3.10
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    docker:
      - image: cimg/openjdk:8.0
      - image: cimg/base:stable
    working_directory: ~/^repo
    steps:
      - checkout
      - run:
          name: Migrate prod env
          command: cat /dev/null | sbt -Dfw.user=$PROD_MYSQL_USER -Dfw.pass=$PROD_MYSQL_PASS -Dfw.locations=db/migration -Dfw.host=$PROD_MYSQL_URI "flywayMigrate"

  publish-arbiter2-image:
    docker:
      - image: cimg/openjdk:8.0
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load docker image
          command: docker load -i /tmp/workspace/image_arbiter2.tar
      - run:
          name: Login to dockerhub
          command: cat /dev/null | echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Publish new docker image
          command: cat /dev/null | docker push mairo/arbiter2:latest

  redeploy-services:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: echo $SSH_IDENTITY
      - run:
          name: Update known hosts
          command: ssh-keyscan -H $HOST_TO_DEPLOY >> ~/.ssh/known_hosts
      - run:
          name: Redeploy images
          command: ssh $SSH_IDENTITY 'cd arbiter_infra && zx deployer.mjs'

workflows:
  version: 2
  run-tests:
    jobs:
      - test:
          context: myctx
  deploy-prod:
    jobs:
      - test:
          context: myctx
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
      - build-jar:
          context: myctx
          requires:
            - test
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
      - migrate-prod-mysq:
          context: myctx
          requires:
            - build-jar
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
      - publish-arbiter2-image:
          context: myctx
          requires:
            - build-jar
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
      - redeploy-services:
          context: myctx
          requires:
            - publish-arbiter2-image
            - migrate-prod-mysq
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/            