version: 2
jobs:
  test-build-soos:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/buildpack-deps:stretch
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: arbiter
          MYSQL_USER: dev
          MYSQL_PASSWORD: password
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      SBT_VERSION: 1.3.10
      SOOS_IMAGE_NAME: mairo/soos
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Prepare mysql for tests
          command: cat /dev/null | sbt soos/flywayClean soos/flywayMigrate
      - run:
          name: Prepare jar
          command: cat /dev/null | sbt soos/clean soos/assembly

  test-build-mabel:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      SBT_VERSION: 1.3.10
      MABEL_IMAGE_NAME: mairo/mabel
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Prepare jar
          command: cat /dev/null | sbt mabel/clean mabel/assembly

  build-soos:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/buildpack-deps:stretch
      - image: circleci/mysql:8.0.4
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASS
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: arbiter
          MYSQL_USER: dev
          MYSQL_PASSWORD: password
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      SBT_VERSION: 1.3.10
      SOOS_IMAGE_NAME: mairo/soos
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Prepare mysql for tests
          command: cat /dev/null | sbt soos/flywayClean soos/flywayMigrate
      - run:
          name: Prepare jar
          command: cat /dev/null | sbt soos/clean soos/assembly
      - setup_remote_docker
      - run:
          name: Build docker image
          #          command: docker build -t $SOOS_IMAGE_NAME:dev-${CIRCLE_SHA1:0:8} services/soos
          command: docker build -t $SOOS_IMAGE_NAME:latest services/soos
      - run:
          name: Save docker image
          command: docker save -o image_soos.tar $SOOS_IMAGE_NAME:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image_soos.tar

  build-mabel:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      SBT_VERSION: 1.3.10
      MABEL_IMAGE_NAME: mairo/mabel
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Prepare jar
          command: cat /dev/null | sbt mabel/clean mabel/assembly
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t $MABEL_IMAGE_NAME:latest services/mabel
      - run:
          name: Save docker image
          command: docker save -o image_mabel.tar $MABEL_IMAGE_NAME:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image_mabel.tar

  build-dipper:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    environment:
      BOT_IMAGE_NAME: mairo/dipper
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker
      - run: cd services/dipper && docker build -t $BOT_IMAGE_NAME:latest .
      - run: cd services/dipper && docker save -o ../../image_dipper.tar $BOT_IMAGE_NAME:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image_dipper.tar

  migrate-prod-mysq:
    environment:
      # Customize the JVM maximum heap limit
      SBT_VERSION: 1.3.10
      SOOS_IMAGE_NAME: mairo/soos
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Migrate prod env
          command: cat /dev/null | sbt -Dfw.user=$PROD_MYSQL_USER -Dfw.pass=$PROD_MYSQL_PASS -Dfw.locations=db/migration -Dfw.host=$PROD_MYSQL_URI "soos/flywayMigrate"

  publish-soos-image:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load docker image
          command: docker load -i /tmp/workspace/image_soos.tar
      - run:
          name: Login to dockerhub
          command: cat /dev/null | echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Publish new docker image
          command: cat /dev/null | docker push mairo/soos:latest

  publish-mabel-image:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load docker image
          command: docker load -i /tmp/workspace/image_mabel.tar
      - run:
          name: Login to dockerhub
          command: cat /dev/null | echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Publish new docker image
          command: cat /dev/null | docker push mairo/mabel:latest

  publish-dipper-image:
    environment:
      BOT_IMAGE_NAME: mairo/dipper
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker load -i /tmp/workspace/image_dipper.tar
      - run: cat /dev/null | docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
      - run: cat /dev/null | docker push mairo/dipper:latest

  redeploy-services:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - add_ssh_keys
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: echo $SSH_IDENTITY
      - run:
          name: Update known hosts
          command: ssh-keyscan -H $HOST_TO_DEPLOY >> ~/.ssh/known_hosts
      - run:
          name: Redeploy images
          command: ssh $SSH_IDENTITY 'cd arbiter_infra && zx deployer.mjs'

workflows:
  version: 2
  build-master:
    jobs:
      - test-build-soos:
          context: myctx
          filters:
            branches:
              ignore:
                - dev
      - test-build-mabel:
          context: myctx
          filters:
            branches:
              ignore:
                - dev
      - build-soos:
          context: myctx
          filters:
            branches:
              only:
                - dev
      - migrate-prod-mysq:
          context: myctx
          requires:
            - build-soos
          filters:
            branches:
              only:
                - dev
      - publish-soos-image:
          context: myctx
          requires:
            - build-soos
          filters:
            branches:
              only:
                - dev
      - build-mabel:
          context: myctx
          filters:
            branches:
              only:
                - dev
      - publish-mabel-image:
          context: myctx
          requires:
            - build-mabel
          filters:
            branches:
              only:
                - dev
      - build-dipper:
          context: myctx
          filters:
            branches:
              only:
                - dev
      - publish-dipper-image:
          context: myctx
          requires:
            - build-dipper
          filters:
            branches:
              only:
                - dev
      - redeploy-services:
          context: myctx
          requires:
            - publish-soos-image
            - publish-mabel-image
            - publish-dipper-image
          filters:
            branches:
              only:
                - dev