//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.14")
addSbtPlugin("io.spray"              % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.eed3si9n"          % "sbt-assembly" % "0.14.10")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"   % "7.4.0")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt" % "2.4.3")
